### ISSUE TITLE
Upgrade to @sinonjs/referee@6.0.2 and remove @sinonjs/formatio

### ISSUE THREAD

**Issue by mroderick** [sinonjs/referee-sinon#97]
Now that `@sinonjs/referee@6.0.2` has been released, which removes `@sinonjs/formatio`, we can also remove `@sinonjs/formatio` as a dependency of this package.

**Comment by mantoni** [comment]
I have all the integration waiting on my machine already 😉☀️. Will push tonight.

**Comment by mroderick** [comment]
Sweet!
